// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pertamina.Website_KPI.Domain.Entities
{
    public partial class LogActivitas
    {
        public string Description { get; set; }
        public string Menu { get; set; }
        public string User { get; set; }
        public string Role { get; set; }
        public string Action { get; set; }
        public string LogDate { get; set; }
    }
}