// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pertamina.Website_KPI.Domain.Entities
{
    public partial class TbltInovasiList
    {
        public int? Id { get; set; }
        public string Filetitle { get; set; }
        public string Filapath { get; set; }
        public DateTime? InsertDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public bool? IsDeleted { get; set; }
    }
}