// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pertamina.Website_KPI.Domain.Entities
{
    public partial class TbltSertifikat
    {
        public int? Id { get; set; }
        public string TitlePenghargaan { get; set; }
        public string Descr { get; set; }
        public string Penerima { get; set; }
        public string Pemberi { get; set; }
        public DateTime? PenghargaanDate { get; set; }
        public DateTime? InsertDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public bool? IsDeleted { get; set; }
    }
}