// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pertamina.Website_KPI.Domain.Entities
{
    public partial class TbltStruktur1
    {
        public string Title { get; set; }
        public string Descr1 { get; set; }
        public string Descr2 { get; set; }
        public string Imgtitle { get; set; }
        public string Imgpath { get; set; }
        public string Imgdescr { get; set; }
        public DateTime? InsertDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public bool? IsDeleted { get; set; }
    }
}