// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pertamina.Website_KPI.Domain.Entities
{
    public partial class TbltDireksi
    {
        public int? Id { get; set; }
        public string Nama { get; set; }
        public string Imgpath { get; set; }
        public string Title { get; set; }
        public string Flag { get; set; }
        public DateTime? InsertDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public bool? IsDeleted { get; set; }
    }
}