// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pertamina.Website_KPI.Domain.Entities
{
    public partial class TbltStruktur2card
    {
        public int? Id { get; set; }
        public string Refinary { get; set; }
        public string Region { get; set; }
        public string HoAddress { get; set; }
        public string Telp { get; set; }
        public string Fax { get; set; }
        public string Telex { get; set; }
        public string Email { get; set; }
        public DateTime? InsertDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public bool? IsDeleted { get; set; }
    }
}