// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pertamina.Website_KPI.Domain.Entities
{
    public partial class TbltInisiatif
    {
        public string Title { get; set; }
        public string Descr { get; set; }
    }
}